### ISSUE TITLE
Log lịch sử thay đổi thông tin của user

### ISSUE THREAD

**Issue by hanvanloi** [hanvanloi/shipchung#17]
- Log
  - Thay đổi thông tin tài khoản Ngan Lượng
  - Thay đổi thông tin tài khoản Ngân Hàng
- Hiển thị thay đổi này trong quản trị của Appsystem

**Comment by mrtang** [comment]
close

**Comment by hanvanloi** [comment]
Link quản trị lịch sử này ở đâu? Close phải có nội dung đã làm chứ Hoàng Anh?

**Comment by mrtang** [comment]
Link quản trị trong appsystem phần thành viên. Đã phân tab
