### ISSUE TITLE
Thêm giao dịch cân bằng số dư tiền thu hộ với phí vận chuyển

### ISSUE THREAD

**Issue by hanvanloi** [hanvanloi/shipchung#37]
- Mã: BALANCE
- Label: Đối trừ công nợ
- Thực thiện
  - Giao dịch chuyển tiền từ tài khoản thu hộ của KH về tài khoản mới là: balance@shipchung.vn

**Comment by tkien** [comment]
http://localhost/shipchung/frontend/api/Accounting/AccountingBalance
