### ISSUE TITLE
Thêm dịch vụ hỏa tốc

### ISSUE THREAD

**Issue by hanvanloi** [hanvanloi/shipchung#5]
- Căn cứ vào bảng giá để đưa ra dịch vụ hỏa tốc
- Có 2 hãng vận chuyển mới sẽ hỗ trợ dịch vụ này
- Vanchuyen24 HN
- 123giao: HCM

Căn cứ vào bảng giá của từng hãng để tính phí hvc

**Comment by tkien** [comment]
tạm thời đóng vì 123 giao có bảng giá còn vc24 ko có
