### ISSUE TITLE
Quản lý vận đơn Lamido

### ISSUE THREAD

**Issue by hanvanloi** [hanvanloi/shipchung#57]
- Xây dưng màn hình report danh sách vận đơn cho Lamido
- Cấp tài khoản cho Lamido đăng nhập vào xem thông tin các vận đơn phát sinh từ Lamido

Chú ý:
- Xây dựng page riêng cho đối tác dạng như CDT, Lamido
- Filter vận đơn theo Domain hoặc từ khoá L4mido trong trường Tên hàng hoá và Mô tả hàng hoá

**Comment by mrtang** [comment]
http://mn.shipchung.vn/pickup/PickupMerchant

close
