### ISSUE TITLE
Kết thúc chương trình khuyến mại

### ISSUE THREAD

**Issue by hanvanloi** [hanvanloi/shipchung#66]
- Tắt toàn bộ thông báo giảm giá 15% cho tất cả khách hàng
- Kiểm tra lại toàn bộ API tính phí, dừng toàn bộ khuyến mại cho các khách hàng bình thường
- Các khách hàng đang áp dụng khuyến mại theo cấu hình sẽ áp dụng mức khuyến mại mặc định là 5% cho tất cả đơn hàng
- Các thông tin khuyến mại marketing đang thông báo thay đổi thông điệp cho phù 
- Lan Anh phối hợp cung cấp bảng giá cho CDT để Kiên kiểm tra lại
- Chốt thời điểm dừng khuyến mại và upload code vào 21h tối nay.

**Comment by tkien** [comment]
done!
